services: 
  web:
    depends_on:
      - api

    build:
      context: ./client-react
      dockerfile: Dockerfile.prod
    image: hardik8195/client
    ports:
      - "80:80"

  api:
    build:
      context: ./server-side
      dockerfile: Dockerfile
    image: hardik8195/server
    env_file:
      - ./server-side/.env
    
    networks:
      - app-network

  nginx:
    image: nginx
    ports: 
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
  
 

