apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
   - name: api
     image: hardik8195/api
     ports:
      - name: server-port
        containerPort: 8080
