apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
   - name: web
     image: hardik8195/web
     ports:
      - name: web-port
        containerPort: 80
